pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    instagram_icon:
                        items: {  }
                        medias: {  }
                        name: instagram_icon
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1719398304
                        creationDate: 1719398304
                        preserveAnimation: false
