pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    original:
                        items: {  }
                        medias: {  }
                        name: original
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1729850755
                        creationDate: 1729850749
                        preserveAnimation: false
