pimcore:
    objects:
        custom_layouts:
            definitions:
                9775f6d3-211e-4dc7-85e6-6108c4c27d82:
                    id: 9775f6d3-211e-4dc7-85e6-6108c4c27d82
                    name: layouttest
                    description: ''
                    creationDate: 1718252173
                    modificationDate: 1722593279
                    userOwner: 2
                    classId: '1'
                    layoutDefinitions:
                        name: pimcore_root
                        type: null
                        region: null
                        title: null
                        width: 0
                        height: 0
                        collapsible: false
                        collapsed: false
                        bodyStyle: null
                        datatype: layout
                        children:
                            -
                                name: Layout
                                type: null
                                region: null
                                title: ''
                                width: ''
                                height: ''
                                collapsible: false
                                collapsed: false
                                bodyStyle: ''
                                datatype: layout
                                children:
                                    -
                                        name: options
                                        title: Options
                                        tooltip: ''
                                        mandatory: false
                                        noteditable: false
                                        index: false
                                        locked: false
                                        style: ''
                                        permissions: null
                                        fieldtype: select
                                        relationType: false
                                        invisible: false
                                        visibleGridView: false
                                        visibleSearch: false
                                        options: {  }
                                        defaultValue: ''
                                        columnLength: 190
                                        dynamicOptions: false
                                        defaultValueGenerator: ''
                                        width: ''
                                        optionsProviderType: configure
                                        optionsProviderClass: ''
                                        optionsProviderData: ''
                                        datatype: data
                                locked: false
                                fieldtype: panel
                                layout: null
                                border: false
                                icon: ''
                                labelWidth: 100
                                labelAlign: left
                        locked: false
                        fieldtype: panel
                        layout: null
                        border: false
                        icon: null
                        labelWidth: 100
                        labelAlign: left
                    default: 0
